# -----------------------------------------------------------
# ads1299 GUI monitoring software v-1.0
#
# Created by: PyQt5 UI code generator 5.15.0
#
# (C) 2020 Aryan Akbarpour, Sheffield, UK
# Released under MIT License
# Email aryan.akr@yahoo.com
# -----------------------------------------------------------


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LeadoffStatus(object):
    def setupUi(self, LeadoffStatus):
        LeadoffStatus.setObjectName("LeadoffStatus")
        LeadoffStatus.resize(400, 560)
        self.label = QtWidgets.QLabel(LeadoffStatus)
        self.label.setGeometry(QtCore.QRect(130, 20, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(LeadoffStatus)
        self.label_2.setGeometry(QtCore.QRect(20, 130, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(LeadoffStatus)
        self.label_3.setGeometry(QtCore.QRect(120, 130, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(LeadoffStatus)
        self.label_4.setGeometry(QtCore.QRect(320, 130, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(LeadoffStatus)
        self.label_5.setGeometry(QtCore.QRect(220, 130, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(LeadoffStatus)
        self.label_6.setGeometry(QtCore.QRect(320, 230, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(LeadoffStatus)
        self.label_7.setGeometry(QtCore.QRect(120, 230, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(LeadoffStatus)
        self.label_8.setGeometry(QtCore.QRect(220, 230, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(LeadoffStatus)
        self.label_9.setGeometry(QtCore.QRect(20, 230, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.statusChannel1P = QtWidgets.QLabel(LeadoffStatus)
        self.statusChannel1P.setGeometry(QtCore.QRect(20, 160, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.statusChannel1P.setFont(font)
        self.statusChannel1P.setObjectName("statusChannel1P")
        self.statusChannel2P = QtWidgets.QLabel(LeadoffStatus)
        self.statusChannel2P.setGeometry(QtCore.QRect(120, 160, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.statusChannel2P.setFont(font)
        self.statusChannel2P.setObjectName("statusChannel2P")
        self.statusChannel3P = QtWidgets.QLabel(LeadoffStatus)
        self.statusChannel3P.setGeometry(QtCore.QRect(220, 160, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.statusChannel3P.setFont(font)
        self.statusChannel3P.setObjectName("statusChannel3P")
        self.statusChannel4P = QtWidgets.QLabel(LeadoffStatus)
        self.statusChannel4P.setGeometry(QtCore.QRect(320, 160, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.statusChannel4P.setFont(font)
        self.statusChannel4P.setObjectName("statusChannel4P")
        self.statusChannel5P = QtWidgets.QLabel(LeadoffStatus)
        self.statusChannel5P.setGeometry(QtCore.QRect(20, 260, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.statusChannel5P.setFont(font)
        self.statusChannel5P.setObjectName("statusChannel5P")
        self.statusChannel6P = QtWidgets.QLabel(LeadoffStatus)
        self.statusChannel6P.setGeometry(QtCore.QRect(120, 260, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.statusChannel6P.setFont(font)
        self.statusChannel6P.setObjectName("statusChannel6P")
        self.statusChannel7P = QtWidgets.QLabel(LeadoffStatus)
        self.statusChannel7P.setGeometry(QtCore.QRect(220, 260, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.statusChannel7P.setFont(font)
        self.statusChannel7P.setObjectName("statusChannel7P")
        self.statusChannel8P = QtWidgets.QLabel(LeadoffStatus)
        self.statusChannel8P.setGeometry(QtCore.QRect(320, 260, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.statusChannel8P.setFont(font)
        self.statusChannel8P.setObjectName("statusChannel8P")
        self.label_10 = QtWidgets.QLabel(LeadoffStatus)
        self.label_10.setGeometry(QtCore.QRect(320, 360, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(LeadoffStatus)
        self.label_11.setGeometry(QtCore.QRect(220, 460, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(LeadoffStatus)
        self.label_12.setGeometry(QtCore.QRect(120, 360, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.statusChannel8N = QtWidgets.QLabel(LeadoffStatus)
        self.statusChannel8N.setGeometry(QtCore.QRect(320, 490, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.statusChannel8N.setFont(font)
        self.statusChannel8N.setObjectName("statusChannel8N")
        self.label_13 = QtWidgets.QLabel(LeadoffStatus)
        self.label_13.setGeometry(QtCore.QRect(20, 460, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.statusChannel2N = QtWidgets.QLabel(LeadoffStatus)
        self.statusChannel2N.setGeometry(QtCore.QRect(120, 390, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.statusChannel2N.setFont(font)
        self.statusChannel2N.setObjectName("statusChannel2N")
        self.label_14 = QtWidgets.QLabel(LeadoffStatus)
        self.label_14.setGeometry(QtCore.QRect(320, 460, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.statusChannel3N = QtWidgets.QLabel(LeadoffStatus)
        self.statusChannel3N.setGeometry(QtCore.QRect(220, 390, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.statusChannel3N.setFont(font)
        self.statusChannel3N.setObjectName("statusChannel3N")
        self.label_15 = QtWidgets.QLabel(LeadoffStatus)
        self.label_15.setGeometry(QtCore.QRect(120, 460, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.statusChannel5N = QtWidgets.QLabel(LeadoffStatus)
        self.statusChannel5N.setGeometry(QtCore.QRect(20, 490, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.statusChannel5N.setFont(font)
        self.statusChannel5N.setObjectName("statusChannel5N")
        self.label_16 = QtWidgets.QLabel(LeadoffStatus)
        self.label_16.setGeometry(QtCore.QRect(220, 360, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.statusChannel7N = QtWidgets.QLabel(LeadoffStatus)
        self.statusChannel7N.setGeometry(QtCore.QRect(220, 490, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.statusChannel7N.setFont(font)
        self.statusChannel7N.setObjectName("statusChannel7N")
        self.statusChannel1N = QtWidgets.QLabel(LeadoffStatus)
        self.statusChannel1N.setGeometry(QtCore.QRect(20, 390, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.statusChannel1N.setFont(font)
        self.statusChannel1N.setObjectName("statusChannel1N")
        self.statusChannel6N = QtWidgets.QLabel(LeadoffStatus)
        self.statusChannel6N.setGeometry(QtCore.QRect(120, 490, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.statusChannel6N.setFont(font)
        self.statusChannel6N.setObjectName("statusChannel6N")
        self.label_17 = QtWidgets.QLabel(LeadoffStatus)
        self.label_17.setGeometry(QtCore.QRect(20, 360, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.statusChannel4N = QtWidgets.QLabel(LeadoffStatus)
        self.statusChannel4N.setGeometry(QtCore.QRect(320, 390, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.statusChannel4N.setFont(font)
        self.statusChannel4N.setObjectName("statusChannel4N")
        self.label_18 = QtWidgets.QLabel(LeadoffStatus)
        self.label_18.setGeometry(QtCore.QRect(20, 85, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(LeadoffStatus)
        self.label_19.setGeometry(QtCore.QRect(20, 320, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")

        self.retranslateUi(LeadoffStatus)
        QtCore.QMetaObject.connectSlotsByName(LeadoffStatus)

    def retranslateUi(self, LeadoffStatus):
        _translate = QtCore.QCoreApplication.translate
        LeadoffStatus.setWindowTitle(_translate("LeadoffStatus", "Form"))
        self.label.setText(_translate("LeadoffStatus", "Lead-Off Status"))
        self.label_2.setText(_translate("LeadoffStatus", "Channel 1"))
        self.label_3.setText(_translate("LeadoffStatus", "Channel 2"))
        self.label_4.setText(_translate("LeadoffStatus", "Channel 4"))
        self.label_5.setText(_translate("LeadoffStatus", "Channel 3"))
        self.label_6.setText(_translate("LeadoffStatus", "Channel 8"))
        self.label_7.setText(_translate("LeadoffStatus", "Channel 6"))
        self.label_8.setText(_translate("LeadoffStatus", "Channel 7"))
        self.label_9.setText(_translate("LeadoffStatus", "Channel 5"))
        self.statusChannel1P.setText(_translate("LeadoffStatus", "Off"))
        self.statusChannel2P.setText(_translate("LeadoffStatus", "Off"))
        self.statusChannel3P.setText(_translate("LeadoffStatus", "Off"))
        self.statusChannel4P.setText(_translate("LeadoffStatus", "Off"))
        self.statusChannel5P.setText(_translate("LeadoffStatus", "Off"))
        self.statusChannel6P.setText(_translate("LeadoffStatus", "Off"))
        self.statusChannel7P.setText(_translate("LeadoffStatus", "Off"))
        self.statusChannel8P.setText(_translate("LeadoffStatus", "Off"))
        self.label_10.setText(_translate("LeadoffStatus", "Channel 4"))
        self.label_11.setText(_translate("LeadoffStatus", "Channel 7"))
        self.label_12.setText(_translate("LeadoffStatus", "Channel 2"))
        self.statusChannel8N.setText(_translate("LeadoffStatus", "Off"))
        self.label_13.setText(_translate("LeadoffStatus", "Channel 5"))
        self.statusChannel2N.setText(_translate("LeadoffStatus", "Off"))
        self.label_14.setText(_translate("LeadoffStatus", "Channel 8"))
        self.statusChannel3N.setText(_translate("LeadoffStatus", "Off"))
        self.label_15.setText(_translate("LeadoffStatus", "Channel 6"))
        self.statusChannel5N.setText(_translate("LeadoffStatus", "Off"))
        self.label_16.setText(_translate("LeadoffStatus", "Channel 3"))
        self.statusChannel7N.setText(_translate("LeadoffStatus", "Off"))
        self.statusChannel1N.setText(_translate("LeadoffStatus", "Off"))
        self.statusChannel6N.setText(_translate("LeadoffStatus", "Off"))
        self.label_17.setText(_translate("LeadoffStatus", "Channel 1"))
        self.statusChannel4N.setText(_translate("LeadoffStatus", "Off"))
        self.label_18.setText(_translate("LeadoffStatus", "Positives:"))
        self.label_19.setText(_translate("LeadoffStatus", "Negatives:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LeadoffStatus = QtWidgets.QWidget()
    ui = Ui_LeadoffStatus()
    ui.setupUi(LeadoffStatus)
    LeadoffStatus.show()
    sys.exit(app.exec_())
