# -----------------------------------------------------------
# ads1299 GUI monitoring software v-1.0
#
# Created by: PyQt5 UI code generator 5.15.0
#
# (C) 2020 Aryan Akbarpour, Sheffield, UK
# Released under MIT License
# Email aryan.akr@yahoo.com
# -----------------------------------------------------------

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProfileRegistration(object):
    def setupUi(self, ProfileRegistration):
        ProfileRegistration.setObjectName("ProfileRegistration")
        ProfileRegistration.resize(752, 598)
        self.label_20 = QtWidgets.QLabel(ProfileRegistration)
        self.label_20.setGeometry(QtCore.QRect(330, 430, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_16 = QtWidgets.QLabel(ProfileRegistration)
        self.label_16.setGeometry(QtCore.QRect(460, 260, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_8 = QtWidgets.QLabel(ProfileRegistration)
        self.label_8.setGeometry(QtCore.QRect(460, 140, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.config1_field = QtWidgets.QLineEdit(ProfileRegistration)
        self.config1_field.setGeometry(QtCore.QRect(40, 160, 113, 20))
        self.config1_field.setObjectName("config1_field")
        self.label_11 = QtWidgets.QLabel(ProfileRegistration)
        self.label_11.setGeometry(QtCore.QRect(320, 200, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(ProfileRegistration)
        self.label_12.setGeometry(QtCore.QRect(460, 200, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_6 = QtWidgets.QLabel(ProfileRegistration)
        self.label_6.setGeometry(QtCore.QRect(180, 140, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.ch4_field = QtWidgets.QLineEdit(ProfileRegistration)
        self.ch4_field.setGeometry(QtCore.QRect(320, 220, 113, 20))
        self.ch4_field.setObjectName("ch4_field")
        self.config3_field = QtWidgets.QLineEdit(ProfileRegistration)
        self.config3_field.setGeometry(QtCore.QRect(320, 160, 113, 20))
        self.config3_field.setObjectName("config3_field")
        self.biassensn_field = QtWidgets.QLineEdit(ProfileRegistration)
        self.biassensn_field.setGeometry(QtCore.QRect(460, 280, 113, 20))
        self.biassensn_field.setObjectName("biassensn_field")
        self.label_17 = QtWidgets.QLabel(ProfileRegistration)
        self.label_17.setGeometry(QtCore.QRect(600, 260, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_7 = QtWidgets.QLabel(ProfileRegistration)
        self.label_7.setGeometry(QtCore.QRect(320, 140, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label = QtWidgets.QLabel(ProfileRegistration)
        self.label.setGeometry(QtCore.QRect(240, 50, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.ch5_field = QtWidgets.QLineEdit(ProfileRegistration)
        self.ch5_field.setGeometry(QtCore.QRect(460, 220, 113, 20))
        self.ch5_field.setObjectName("ch5_field")
        self.label_18 = QtWidgets.QLabel(ProfileRegistration)
        self.label_18.setGeometry(QtCore.QRect(180, 320, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.ch6_field = QtWidgets.QLineEdit(ProfileRegistration)
        self.ch6_field.setGeometry(QtCore.QRect(600, 220, 113, 20))
        self.ch6_field.setObjectName("ch6_field")
        self.misc1_field = QtWidgets.QLineEdit(ProfileRegistration)
        self.misc1_field.setGeometry(QtCore.QRect(320, 340, 113, 20))
        self.misc1_field.setObjectName("misc1_field")
        self.ch8_field = QtWidgets.QLineEdit(ProfileRegistration)
        self.ch8_field.setGeometry(QtCore.QRect(180, 280, 113, 20))
        self.ch8_field.setObjectName("ch8_field")
        self.loffsensp_field = QtWidgets.QLineEdit(ProfileRegistration)
        self.loffsensp_field.setGeometry(QtCore.QRect(600, 280, 113, 20))
        self.loffsensp_field.setObjectName("loffsensp_field")
        self.label_22 = QtWidgets.QLabel(ProfileRegistration)
        self.label_22.setGeometry(QtCore.QRect(320, 320, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(ProfileRegistration)
        self.label_23.setGeometry(QtCore.QRect(460, 320, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.misc2_field = QtWidgets.QLineEdit(ProfileRegistration)
        self.misc2_field.setGeometry(QtCore.QRect(460, 340, 113, 20))
        self.misc2_field.setObjectName("misc2_field")
        self.label_3 = QtWidgets.QLabel(ProfileRegistration)
        self.label_3.setGeometry(QtCore.QRect(40, 200, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_19 = QtWidgets.QLabel(ProfileRegistration)
        self.label_19.setGeometry(QtCore.QRect(40, 370, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.loffsensn_field = QtWidgets.QLineEdit(ProfileRegistration)
        self.loffsensn_field.setGeometry(QtCore.QRect(40, 340, 113, 20))
        self.loffsensn_field.setObjectName("loffsensn_field")
        self.name_field = QtWidgets.QLineEdit(ProfileRegistration)
        self.name_field.setGeometry(QtCore.QRect(290, 460, 161, 20))
        self.name_field.setObjectName("name_field")
        self.loffflip_field = QtWidgets.QLineEdit(ProfileRegistration)
        self.loffflip_field.setGeometry(QtCore.QRect(180, 340, 113, 20))
        self.loffflip_field.setObjectName("loffflip_field")
        self.label_2 = QtWidgets.QLabel(ProfileRegistration)
        self.label_2.setGeometry(QtCore.QRect(40, 140, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.loff_field = QtWidgets.QLineEdit(ProfileRegistration)
        self.loff_field.setGeometry(QtCore.QRect(460, 160, 113, 20))
        self.loff_field.setObjectName("loff_field")
        self.label_21 = QtWidgets.QLabel(ProfileRegistration)
        self.label_21.setGeometry(QtCore.QRect(600, 320, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.ch7_field = QtWidgets.QLineEdit(ProfileRegistration)
        self.ch7_field.setGeometry(QtCore.QRect(40, 280, 113, 20))
        self.ch7_field.setObjectName("ch7_field")
        self.label_4 = QtWidgets.QLabel(ProfileRegistration)
        self.label_4.setGeometry(QtCore.QRect(40, 260, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(ProfileRegistration)
        self.label_5.setGeometry(QtCore.QRect(40, 320, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.ch2_field = QtWidgets.QLineEdit(ProfileRegistration)
        self.ch2_field.setGeometry(QtCore.QRect(40, 220, 113, 20))
        self.ch2_field.setObjectName("ch2_field")
        self.label_10 = QtWidgets.QLabel(ProfileRegistration)
        self.label_10.setGeometry(QtCore.QRect(180, 200, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gpio_field = QtWidgets.QLineEdit(ProfileRegistration)
        self.gpio_field.setGeometry(QtCore.QRect(600, 340, 113, 20))
        self.gpio_field.setObjectName("gpio_field")
        self.label_15 = QtWidgets.QLabel(ProfileRegistration)
        self.label_15.setGeometry(QtCore.QRect(320, 260, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.config2_field = QtWidgets.QLineEdit(ProfileRegistration)
        self.config2_field.setGeometry(QtCore.QRect(180, 160, 113, 20))
        self.config2_field.setObjectName("config2_field")
        self.create_profile_btn = QtWidgets.QPushButton(ProfileRegistration)
        self.create_profile_btn.setGeometry(QtCore.QRect(280, 510, 181, 41))
        self.create_profile_btn.setObjectName("create_profile_btn")
        self.biassensp_field = QtWidgets.QLineEdit(ProfileRegistration)
        self.biassensp_field.setGeometry(QtCore.QRect(320, 280, 113, 20))
        self.biassensp_field.setObjectName("biassensp_field")
        self.ch1_field = QtWidgets.QLineEdit(ProfileRegistration)
        self.ch1_field.setGeometry(QtCore.QRect(600, 160, 113, 20))
        self.ch1_field.setObjectName("ch1_field")
        self.label_14 = QtWidgets.QLabel(ProfileRegistration)
        self.label_14.setGeometry(QtCore.QRect(180, 260, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_13 = QtWidgets.QLabel(ProfileRegistration)
        self.label_13.setGeometry(QtCore.QRect(600, 200, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.ch3_field = QtWidgets.QLineEdit(ProfileRegistration)
        self.ch3_field.setGeometry(QtCore.QRect(180, 220, 113, 20))
        self.ch3_field.setObjectName("ch3_field")
        self.label_9 = QtWidgets.QLabel(ProfileRegistration)
        self.label_9.setGeometry(QtCore.QRect(600, 140, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.config4_field = QtWidgets.QLineEdit(ProfileRegistration)
        self.config4_field.setGeometry(QtCore.QRect(40, 390, 113, 20))
        self.config4_field.setObjectName("config4_field")

        self.retranslateUi(ProfileRegistration)
        QtCore.QMetaObject.connectSlotsByName(ProfileRegistration)

    def retranslateUi(self, ProfileRegistration):
        _translate = QtCore.QCoreApplication.translate
        ProfileRegistration.setWindowTitle(_translate("ProfileRegistration", "Form"))
        self.label_20.setText(_translate("ProfileRegistration", "Profile Name"))
        self.label_16.setText(_translate("ProfileRegistration", "BIAS_SENSN"))
        self.label_8.setText(_translate("ProfileRegistration", "LOFF"))
        self.config1_field.setText(_translate("ProfileRegistration", "10010110"))
        self.label_11.setText(_translate("ProfileRegistration", "CH4SET"))
        self.label_12.setText(_translate("ProfileRegistration", "CH5SET"))
        self.label_6.setText(_translate("ProfileRegistration", "CONFIG2"))
        self.ch4_field.setText(_translate("ProfileRegistration", "01100001"))
        self.config3_field.setText(_translate("ProfileRegistration", "01100000"))
        self.biassensn_field.setText(_translate("ProfileRegistration", "00000000"))
        self.label_17.setText(_translate("ProfileRegistration", "LOFF_SENSP"))
        self.label_7.setText(_translate("ProfileRegistration", "CONFIG3"))
        self.label.setText(_translate("ProfileRegistration", "Create New Control Profile"))
        self.ch5_field.setText(_translate("ProfileRegistration", "01100001"))
        self.label_18.setText(_translate("ProfileRegistration", "LOFF_FLIP"))
        self.ch6_field.setText(_translate("ProfileRegistration", "01100001"))
        self.misc1_field.setText(_translate("ProfileRegistration", "00000000"))
        self.ch8_field.setText(_translate("ProfileRegistration", "01100001"))
        self.loffsensp_field.setText(_translate("ProfileRegistration", "00000000"))
        self.label_22.setText(_translate("ProfileRegistration", "MISC1"))
        self.label_23.setText(_translate("ProfileRegistration", "MISC2"))
        self.misc2_field.setText(_translate("ProfileRegistration", "00000000"))
        self.label_3.setText(_translate("ProfileRegistration", "CH2SET"))
        self.label_19.setText(_translate("ProfileRegistration", "CONFIG4"))
        self.loffsensn_field.setText(_translate("ProfileRegistration", "00000000"))
        self.name_field.setText(_translate("ProfileRegistration", "NewProfile"))
        self.loffflip_field.setText(_translate("ProfileRegistration", "00000000"))
        self.label_2.setText(_translate("ProfileRegistration", "CONFIG1"))
        self.loff_field.setText(_translate("ProfileRegistration", "00000000"))
        self.label_21.setText(_translate("ProfileRegistration", "GPIO"))
        self.ch7_field.setText(_translate("ProfileRegistration", "01100001"))
        self.label_4.setText(_translate("ProfileRegistration", "CH7SET"))
        self.label_5.setText(_translate("ProfileRegistration", "LOFF_SENSN"))
        self.ch2_field.setText(_translate("ProfileRegistration", "01100001"))
        self.label_10.setText(_translate("ProfileRegistration", "CH3SET"))
        self.gpio_field.setText(_translate("ProfileRegistration", "00001111"))
        self.label_15.setText(_translate("ProfileRegistration", "BIAS_SENP"))
        self.config2_field.setText(_translate("ProfileRegistration", "11000000"))
        self.create_profile_btn.setText(_translate("ProfileRegistration", "Create Register Profile"))
        self.biassensp_field.setText(_translate("ProfileRegistration", "00000000"))
        self.ch1_field.setText(_translate("ProfileRegistration", "01100001"))
        self.label_14.setText(_translate("ProfileRegistration", "CH8SET"))
        self.label_13.setText(_translate("ProfileRegistration", "CH6SET"))
        self.ch3_field.setText(_translate("ProfileRegistration", "01100001"))
        self.label_9.setText(_translate("ProfileRegistration", "CH1SET"))
        self.config4_field.setText(_translate("ProfileRegistration", "00000000"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProfileRegistration = QtWidgets.QWidget()
    ui = Ui_ProfileRegistration()
    ui.setupUi(ProfileRegistration)
    ProfileRegistration.show()
    sys.exit(app.exec_())
